### ISSUE TITLE
go script not working

### ISSUE THREAD

**Issue by CrystalOnScript** [subscriptions-project/encryption#11]
Filing an issue that the `go` script seems to be broken at [https://github.com/subscriptions-project/encryption/tree/master/golang/cmd/gcp_key_gen](https://github.com/subscriptions-project/encryption/tree/master/golang/cmd/gcp_key_gen)

Is there an alternative we can provide?

cc @jeffochoa

**Comment by elijahsoria** [comment]
Seems that the Tink team changed their Google Cloud API months ago: https://github.com/google/tink/commit/55a65a01ef9e466152ceb51e43e3658e0f6e0870#diff-03579a9e37886100a9fd05ae2288d60eL96

I'll update the script to use the new functions.

**Comment by elijahsoria** [comment]
Just verified that the script is working again after the PR submitted last week.
